In [1]:
!pip install pandas numpy matplotlib seaborn plotly sqlalchemy requests scipy jupyter

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: numpy in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: matplotlib in c:\users\admin\appdata\roaming\python\python313\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: plotly in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (6.7.0)
Requirement already satisfied: sqlalchemy in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (2.0.48)
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (2.32.4)
Requirement already satisfied: scipy in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (1.16.0)
Requirement already satisfied: jupyter in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (1.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from plotly) (2.22.0)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from requests) (2025.7.14)
Requirement already satisfied: notebook in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (7.5.6)
Requirement already satisfied: jupyter-console in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (7.17.1)
Requirement already satisfied: ipykernel in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (7.2.0)
Requirement already satisfied: ipywidgets in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (8.1.8)
Requirement already satisfied: jupyterlab in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (4.5.7)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (9.14.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (0.2.2)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil>=5.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (6.5.6)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (5.15.0)
Requirement already satisfied: colorama>=0.4.4 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel->jupyter) (0.8.7)
Requirement already satisfied: platformdirs>=2.5 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.10.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipywidgets->jupyter) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from ipywidgets->jupyter) (3.0.16)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (2.19.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (82.0.1)
Requirement already satisfied: anyio in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.9.0)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.25.0)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.9.0)
Requirement already satisfied: babel>=2.10 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.14.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2026.5.1)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.2)
Requirement already satisfied: rfc3339-validator in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.3.0)
Requirement already satisfied: defusedxml in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (3.2.1)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21.2)
Requirement already satisfied: lark>=1.2.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.0)
Requirement already satisfied: pycparser in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.8.1)
Requirement already satisfied: arrow>=0.15.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.4.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import os

csv_folder = "../data/raw"

csv_files = [f for f in os.listdir(csv_folder) if f.endswith(".csv")]

print("Total CSV files:", len(csv_files))
print(csv_files)

Total CSV files: 16
['01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv', 'axis_bluechip_nav.csv', 'hdfc_top100_nav.csv', 'icici_bluechip_nav.csv', 'kotak_bluechip_nav.csv', 'nippon_large_cap_nav.csv', 'sbi_bluechip_nav.csv']

In [7]:
import pandas as pd
import os

csv_folder = "../data/raw"

for file in os.listdir(csv_folder):
    if file.endswith(".csv"):
        print("\n" + "="*60)
        print("FILE:", file)

        df = pd.read_csv(os.path.join(csv_folder, file))

        print("\nShape:")
        print(df.shape)

        print("\nData Types:")
        print(df.dtypes)

        print("\nFirst 5 Rows:")
        display(df.head())

============================================================
FILE: 01_fund_master.csv

Shape:
(40, 15)

Data Types:
amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

First 5 Rows:

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

============================================================
FILE: 02_nav_history.csv

Shape:
(46000, 3)

Data Types:
amfi_code      int64
date          object
nav          float64
dtype: object

First 5 Rows:

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

============================================================
FILE: 03_aum_by_fund_house.csv

Shape:
(90, 5)

Data Types:
date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

First 5 Rows:

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

============================================================
FILE: 04_monthly_sip_inflows.csv

Shape:
(48, 6)

Data Types:
month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

First 5 Rows:

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

============================================================
FILE: 05_category_inflows.csv

Shape:
(144, 3)

Data Types:
month                object
category             object
net_inflow_crore    float64
dtype: object

First 5 Rows:

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

============================================================
FILE: 06_industry_folio_count.csv

Shape:
(21, 6)

Data Types:
month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

First 5 Rows:

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

============================================================
FILE: 07_scheme_performance.csv

Shape:
(40, 19)

Data Types:
amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

First 5 Rows:

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

============================================================
FILE: 08_investor_transactions.csv

Shape:
(32778, 13)

Data Types:
investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

First 5 Rows:

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

============================================================
FILE: 09_portfolio_holdings.csv

Shape:
(322, 8)

Data Types:
amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

First 5 Rows:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

============================================================
FILE: 10_benchmark_indices.csv

Shape:
(8050, 3)

Data Types:
date            object
index_name      object
close_value    float64
dtype: object

First 5 Rows:

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

============================================================
FILE: axis_bluechip_nav.csv

Shape:
(3566, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date        nav
0  02-06-2026  6158.9665
1  01-06-2026  6156.7532
2  29-05-2026  6151.1139
3  27-05-2026  6146.6118
4  26-05-2026  6144.0004

============================================================
FILE: hdfc_top100_nav.csv

Shape:
(3092, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date       nav
0  02-06-2026  193.1295
1  01-06-2026  192.3195
2  31-05-2026  193.6836
3  29-05-2026  193.6848
4  27-05-2026  195.0501

============================================================
FILE: icici_bluechip_nav.csv

Shape:
(3308, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date       nav
0  02-06-2026  103.5959
1  01-06-2026  103.0948
2  31-05-2026  104.3083
3  29-05-2026  104.3129
4  27-05-2026  105.9296

============================================================
FILE: kotak_bluechip_nav.csv

Shape:
(3302, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date       nav
0  02-06-2026  246.8566
1  01-06-2026  246.9814
2  29-05-2026  248.6673
3  27-05-2026  251.2273
4  26-05-2026  251.2702

============================================================
FILE: nippon_large_cap_nav.csv

Shape:
(3299, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date      nav
0  02-06-2026  97.4783
1  01-06-2026  97.1944
2  29-05-2026  98.4656
3  27-05-2026  99.8092
4  26-05-2026  99.4356

============================================================
FILE: sbi_bluechip_nav.csv

Shape:
(3237, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date       nav
0  02-06-2026  104.7663
1  01-06-2026  104.7025
2  29-05-2026  104.6570
3  27-05-2026  104.5833
4  26-05-2026  104.5269

In [9]:
import pandas as pd
import os

csv_folder = "../data/raw"

for file in os.listdir(csv_folder):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(csv_folder, file))

        print("\n" + "="*60)
        print("FILE:", file)

        print("Missing Values:")
        print(df.isnull().sum())

        print("\nDuplicate Rows:")
        print(df.duplicated().sum())

        print("\nEmpty Columns:")
        empty_cols = df.columns[df.isnull().all()]
        print(list(empty_cols))

============================================================
FILE: 01_fund_master.csv
Missing Values:
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: 02_nav_history.csv
Missing Values:
amfi_code    0
date         0
nav          0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: 03_aum_by_fund_house.csv
Missing Values:
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: 04_monthly_sip_inflows.csv
Missing Values:
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: 05_category_inflows.csv
Missing Values:
month               0
category            0
net_inflow_crore    0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: 06_industry_folio_count.csv
Missing Values:
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: 07_scheme_performance.csv
Missing Values:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: 08_investor_transactions.csv
Missing Values:
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: 09_portfolio_holdings.csv
Missing Values:
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: 10_benchmark_indices.csv
Missing Values:
date           0
index_name     0
close_value    0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: axis_bluechip_nav.csv
Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: hdfc_top100_nav.csv
Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: icici_bluechip_nav.csv
Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: kotak_bluechip_nav.csv
Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: nippon_large_cap_nav.csv
Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

============================================================
FILE: sbi_bluechip_nav.csv
Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

Empty Columns:
[]

In [13]:
import pandas as pd
import os

for file in os.listdir("../data/raw"):
    if file.endswith(".csv"):
        df = pd.read_csv(f"../data/raw/{file}")

        print("\n" + "="*50)
        print("File:", file)

        print("\nMissing Values:")
        print(df.isnull().sum())

        print("\nDuplicate Rows:")
        print(df.duplicated().sum())

==================================================
File: 01_fund_master.csv

Missing Values:
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

Duplicate Rows:
0

==================================================
File: 02_nav_history.csv

Missing Values:
amfi_code    0
date         0
nav          0
dtype: int64

Duplicate Rows:
0

==================================================
File: 03_aum_by_fund_house.csv

Missing Values:
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

Duplicate Rows:
0

==================================================
File: 04_monthly_sip_inflows.csv

Missing Values:
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

Duplicate Rows:
0

==================================================
File: 05_category_inflows.csv

Missing Values:
month               0
category            0
net_inflow_crore    0
dtype: int64

Duplicate Rows:
0

==================================================
File: 06_industry_folio_count.csv

Missing Values:
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

Duplicate Rows:
0

==================================================
File: 07_scheme_performance.csv

Missing Values:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Duplicate Rows:
0

==================================================
File: 08_investor_transactions.csv

Missing Values:
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Duplicate Rows:
0

==================================================
File: 09_portfolio_holdings.csv

Missing Values:
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Duplicate Rows:
0

==================================================
File: 10_benchmark_indices.csv

Missing Values:
date           0
index_name     0
close_value    0
dtype: int64

Duplicate Rows:
0

==================================================
File: axis_bluechip_nav.csv

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

==================================================
File: hdfc_top100_nav.csv

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

==================================================
File: icici_bluechip_nav.csv

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

==================================================
File: kotak_bluechip_nav.csv

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

==================================================
File: nippon_large_cap_nav.csv

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

==================================================
File: sbi_bluechip_nav.csv

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

In [14]:
import requests
import pandas as pd

url = "https://api.mfapi.in/mf/125497"

response = requests.get(url)
data = response.json()

print(data["meta"])

{'fund_house': 'SBI Mutual Fund', 'scheme_type': 'Open Ended Schemes', 'scheme_category': 'Equity Scheme - Small Cap Fund', 'scheme_code': 125497, 'scheme_name': 'SBI Small Cap Fund - Direct Plan - Growth', 'isin_growth': 'INF200K01T51', 'isin_div_reinvestment': None}

In [16]:
nav_df = pd.DataFrame(data["data"])
nav_df.to_csv("../data/raw/hdfc_top100_nav.csv", index=False)

print("Saved successfully")

Saved successfully

In [17]:
import requests
import pandas as pd
import os

# Create folder if it doesn't exist
os.makedirs("data/raw", exist_ok=True)

# Scheme codes and names
schemes = {
    "119551": "sbi_bluechip",
    "120503": "icici_bluechip",
    "118632": "nippon_large_cap",
    "119092": "axis_bluechip",
    "120841": "kotak_bluechip"
}

for scheme_code, fund_name in schemes.items():

    url = f"https://api.mfapi.in/mf/{scheme_code}"

    try:
        response = requests.get(url)
        response.raise_for_status()

        data = response.json()

        nav_df = pd.DataFrame(data["data"])

        file_path = f"data/raw/{fund_name}_nav.csv"

        nav_df.to_csv(file_path, index=False)

        print(f"✓ Saved: {file_path}")

    except Exception as e:
        print(f"✗ Error fetching {fund_name}: {e}")

print("\nAll NAV files downloaded.")

✓ Saved: data/raw/sbi_bluechip_nav.csv
✓ Saved: data/raw/icici_bluechip_nav.csv
✓ Saved: data/raw/nippon_large_cap_nav.csv
✓ Saved: data/raw/axis_bluechip_nav.csv
✓ Saved: data/raw/kotak_bluechip_nav.csv

All NAV files downloaded.

In [18]:
import os

print(os.listdir("data/raw"))

['axis_bluechip_nav.csv', 'icici_bluechip_nav.csv', 'kotak_bluechip_nav.csv', 'nippon_large_cap_nav.csv', 'sbi_bluechip_nav.csv']

In [20]:
import pandas as pd

fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

print(fund_master.columns)

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')

In [21]:
# Total Fund Houses
print("Total Fund Houses:")
print(fund_master["fund_house"].nunique())

print("\nFund Houses:")
print(fund_master["fund_house"].unique())

# Categories
print("\nCategories:")
print(fund_master["category"].unique())

# Sub-Categories
print("\nSub-Categories:")
print(fund_master["sub_category"].unique())

# Risk Categories
print("\nRisk Categories:")
print(fund_master["risk_category"].unique())

Total Fund Houses:
10

Fund Houses:
['SBI Mutual Fund' 'HDFC Mutual Fund' 'ICICI Prudential MF'
 'Nippon India MF' 'Kotak Mahindra MF' 'Axis Mutual Fund'
 'Aditya Birla Sun Life MF' 'UTI Mutual Fund' 'Mirae Asset MF'
 'DSP Mutual Fund']

Categories:
['Equity' 'Debt']

Sub-Categories:
['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']

Risk Categories:
['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

In [ ]:
Fund Master Exploration Summary

- Total Fund Houses: 10
- Total Categories: 2
- Total Sub-Categories: 12
- Risk Categories Present: Low, Moderate, High, Very High

The dataset contains mutual fund schemes from multiple fund houses.
Each scheme is identified using a unique AMFI code.
Categories and sub-categories classify the type of mutual fund.
Risk categories indicate the risk level associated with each scheme.

In [22]:
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")
print(nav_history.columns.tolist())

['amfi_code', 'date', 'nav']

In [24]:
import pandas as pd

fund_master = pd.read_csv("../data/raw/01_fund_master.csv")
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")

In [25]:
fund_codes = set(fund_master["amfi_code"])
nav_codes = set(nav_history["amfi_code"])

matching_codes = fund_codes.intersection(nav_codes)
missing_codes = fund_codes - nav_codes

print("Total AMFI Codes in Fund Master:", len(fund_codes))
print("Total AMFI Codes in NAV History:", len(nav_codes))
print("Matching Codes:", len(matching_codes))
print("Missing Codes:", len(missing_codes))

Total AMFI Codes in Fund Master: 40
Total AMFI Codes in NAV History: 40
Matching Codes: 40
Missing Codes: 0

In [26]:
if len(missing_codes) > 0:
    print("Missing AMFI Codes:")
    print(sorted(list(missing_codes)))
else:
    print("All AMFI codes from fund_master exist in nav_history.")

All AMFI codes from fund_master exist in nav_history.

In [ ]:
AMFI Code Validation

Total AMFI Codes in Fund Master: 40
Total AMFI Codes in NAV History: 40
Matching Codes: 40
Missing Codes: 0

Observation:
Most scheme codes were successfully matched between the datasets. AMFI codes serve as the primary key for linking mutual fund scheme information with NAV records.